### ISSUE TITLE
Section 3 - System Scope and Context

### ISSUE THREAD

**Issue by UO283069** [Arquisoft/lomap_en3a#4]
Develop the section 3, refered to the scope and context of the system, sepcifing the external interfaces that delimit the system from all its communication partners.

The assignment agreed for this section of the documentation has been.

3. System Scope and Context - Both
3.1. Business Context - Guillermo Dylan Carvajal Aza
3.2. Technical Context - Pelayo Reguera García

All the documentation generated will be first revised by the partners that have this task assigned first and then by the complete team.

**Comment by Davidmc07** [comment]
Differences of business context and technical context: 
https://docs.arc42.org/tips/3-10/
