### ISSUE TITLE
Error when running unit tests

### ISSUE THREAD

**Issue by UO283069** [Arquisoft/lomap_en3a#83]
### An error when trying to run the unit tests has been found, this error is not allowing the exeuction of the tests because of an issue with one of the Leaflet modules and how Jest is processing it, or at least that is how I have understanded the following trace:

![First part of the trace](https://user-images.githubusercontent.com/98907563/230735123-b7506d5b-f520-4faa-ac43-77c39a5fc6e0.png)
![Second part of the trace](https://user-images.githubusercontent.com/98907563/230735209-d2982593-5f68-49de-be3e-0770fb526318.png)
After a quick search on StackOverflow, I was able to find someone with this exact same problem: [Link](https://stackoverflow.com/questions/73504569/syntaxerror-unexpected-token-export-from-react-leaflet-while-using-jest)
Unfortunately, I have already tried changing the configuration of our _jest.config.ts_ to what he proposes on the forum, right now it is like this:

```
const esModules = ['@react-leaflet', 'react-leaflet'].join('|');
export default {
    transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
    transform: {
        "^.+\\.tsx?$": "ts-jest"
    },
}
```
I think this is a very important matter and should be taken care as soon as possible, since this prevents us from testing any test that imports any of the Leaflet modules.

Just in case, this is how the test is defined, I do not think this problem is related to the code, but to the configuration, but just to make sure this is how it is coded:

![Test code](https://user-images.githubusercontent.com/98907563/230735577-3074b4c0-da9f-42e8-b7c5-996c39943909.png)

**Comment by UO283069** [comment]
As a small note, I would like to add that this error could possibly be caused by the following (found on StackOverflow), the index.js file of the Leaflet module is compiled into th ESM syntax instead of the CommonJS syntax, which seems to be causing all of the trouble, since Jest is not able to process it. This page offers a way to activate support for ESM on the tests, but I have not been able to try it yet and don't know if it would be recommendable or not: [jestjs.io/docs/ecmascript-modules](https://jestjs.io/docs/ecmascript-modules).

**Comment by uo282892** [comment]
In webapp/package.json, put the following line: 

```typescript
"test": "react-scripts test --transformIgnorePatterns \"node_modules/(?!ol)/\" --coverage",
```

**Comment by UO283069** [comment]
### Thanks!  This seems ti solve the problem for the Leaflet module.
Unfortunatley there seems to be another problem, as another error arises leaving the following trace:

![Error trace](https://user-images.githubusercontent.com/98907563/230917493-e318b9cf-1f96-4df1-ba1e-4f6cb0accb13.png)

I will be looking forward for soultions and keep this thread upadted.

**Comment by UO283428** [comment]
I have seen the error in a repository
https://github.com/inrupt/solid-client-authn-js/issues/1676

**Comment by uo282892** [comment]
Try to append the following in the webapp/src/setUpTests.ts, after the last line:

```typescript
import { TextEncoder, TextDecoder } from 'util';

global.TextEncoder = TextEncoder;
(global as any).textDecoder = TextDecoder;
```

**Comment by UO283069** [comment]
Fantastic, this does finally solve the problems with Jest, it has all been fixed and updated in develop (commit https://github.com/Arquisoft/lomap_en3a/commit/83789466516be01042f95e2e0b2c4fef65087cf1)

**Comment by FdezAriasSara** [comment]
I  got the same exact error using Maps api, so I think is rather a solid library -related issue as you mentioned before (I actually accessed  this issue from there ) 

 I used the solution mentioned here:


> I have seen the error in a repository [inrupt/solid-client-authn-js#1676](https://github.com/inrupt/solid-client-authn-js/issues/1676)
> 
> Use "import { TextEncoder, TextDecoder } from 'util'; global.TextEncoder = TextEncoder; global.TextDecoder = TextDecoder;"

 since 


> Try to append the following in the webapp/src/setUpTests.ts, after the last line:
> 
> ```ts
> import { TextEncoder, TextDecoder } from 'util';
> 
> global.TextEncoder = TextEncoder;
> (global as any).textDecoder = TextDecoder;
> ```

is not working for some reason ( maybe because i use javascript not ts)


thank you !
